"""
Evidence Summary State

Tracks information requirements and retrieved evidence for the Agentic RAG
Orchestrator. Uses SHA-256 hashing for evidence/chunk deduplication.

Key design:
- Compact state — never appends every retrieved chunk to LLM context
- Requirement tracking: REQUIRED → FOUND → VERIFIED → MISSING → CONFLICTING
- SHA-256 dedup: same evidence retrieved again is silently suppressed
- Repeated query suppression: identical queries do not re-trigger retrieval
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Set

logger = logging.getLogger("fte.rag.evidence_summary_state")


# ---------------------------------------------------------------------------
# Requirement status constants
# ---------------------------------------------------------------------------

REQUIRED = "REQUIRED"
FOUND = "FOUND"
VERIFIED = "VERIFIED"
MISSING = "MISSING"
CONFLICTING = "CONFLICTING"


# ---------------------------------------------------------------------------
# Evidence Status constants
# ---------------------------------------------------------------------------

EVIDENCE_PENDING = "PENDING"
EVIDENCE_VERIFIED = "VERIFIED"
EVIDENCE_CONFLICT = "CONFLICT"
EVIDENCE_SUPERSEDED = "SUPERSEDED"
EVIDENCE_REJECTED = "REJECTED"


# ---------------------------------------------------------------------------
# Terminal state constants
# ---------------------------------------------------------------------------

STATE_COMPLETE = "COMPLETE"
STATE_INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
STATE_RETRIEVAL_LIMIT_REACHED = "RETRIEVAL_LIMIT_REACHED"
STATE_UNRESOLVED_CONFLICT = "UNRESOLVED_CONFLICT"
STATE_CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
STATE_EXTRACTION_CORRUPTED = "EXTRACTION_CORRUPTED"
STATE_EXECUTION_TIMEOUT = "EXECUTION_TIMEOUT"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class EvidenceItem:
    """A single piece of evidence from retrieval."""

    fact_id: str = ""
    metric: str = ""
    metric_definition: str = ""
    value: Optional[float] = None
    unit: str = ""
    currency_code: str = ""
    currency_role: str = ""

    # Fix #5 (FX metadata): additive fields, backward compatible.
    # currency_role must stay semantically distinct (REPORTING / FUNCTIONAL /
    # PRESENTATION / TRANSACTION / TAX); FX fields must never be flattened
    # into the currency_code string.
    fx_rate: Optional[float] = None
    fx_source: str = ""
    fx_timestamp: Optional[str] = None

    reporting_period: str = ""
    accounting_basis: str = ""
    scope: str = ""
    source: str = ""
    source_tier: int = 1
    document_id: str = ""
    page_section: str = ""
    source_anchor: str = ""
    confidence: float = 0.0
    verification_status: str = EVIDENCE_PENDING
    evidence_hash: str = ""

    # Fix #2 (scale propagation): additive fields, backward compatible.
    # `value` carries the NORMALIZED magnitude; the original extracted value
    # and its scale/unit metadata are preserved for auditability.
    original_value: Optional[float] = None   # raw extracted value
    scale: str = ""                          # e.g. "crores", "millions", "10^6"
    normalized_value: Optional[float] = None  # value * scale multiplier

    def to_dict(self) -> Dict[str, Any]:
        return {
            "fact_id": self.fact_id,
            "metric": self.metric,
            "metric_definition": self.metric_definition,
            "value": self.value,
            "unit": self.unit,
            "currency_code": self.currency_code,
            "currency_role": self.currency_role,
            "fx_rate": self.fx_rate,
            "fx_source": self.fx_source,
            "fx_timestamp": self.fx_timestamp,
            "reporting_period": self.reporting_period,
            "accounting_basis": self.accounting_basis,
            "scope": self.scope,
            "source": self.source,
            "source_tier": self.source_tier,
            "document_id": self.document_id,
            "source_anchor": self.source_anchor,
            "confidence": self.confidence,
            "verification_status": self.verification_status,
            "evidence_hash": self.evidence_hash,
            "original_value": self.original_value,
            "scale": self.scale,
            "normalized_value": self.normalized_value,
        }


@dataclass
class InformationRequirement:
    """An information requirement generated by the planner."""

    id: str = ""
    description: str = ""
    metric: str = ""
    metric_definition: str = ""
    period: str = ""
    scope: str = ""
    currency: str = ""
    status: str = REQUIRED
    matched_evidence: List[str] = field(default_factory=list)  # evidence hashes
    notes: str = ""


@dataclass
class EvidenceState:
    """Compact internal state for the Agentic RAG loop."""

    # Terminal state
    terminal_state: str = ""
    terminal_reason: str = ""

    # Requirements
    requirements: List[InformationRequirement] = field(default_factory=list)
    satisfied_count: int = 0
    missing_count: int = 0
    conflict_count: int = 0

    # Evidence store
    evidence: Dict[str, EvidenceItem] = field(default_factory=dict)  # hash → item
    evidence_count: int = 0

    # Retrieval tracking
    iterations_used: int = 0
    max_iterations: int = 3
    queries_asked: Set[str] = field(default_factory=set)
    retrieval_log: List[Dict] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "terminal_state": self.terminal_state,
            "terminal_reason": self.terminal_reason,
            "requirements": [r.__dict__ for r in self.requirements],
            "satisfied_count": self.satisfied_count,
            "missing_count": self.missing_count,
            "conflict_count": self.conflict_count,
            "evidence_count": self.evidence_count,
            "iterations_used": self.iterations_used,
            "max_iterations": self.max_iterations,
            "queries_asked": list(self.queries_asked),
        }


# ---------------------------------------------------------------------------
# Evidence Summary State Manager
# ---------------------------------------------------------------------------


class EvidenceSummaryState:
    """
    Manages the compact evidence state for Agentic RAG.

    Responsibilities:
    - Track information requirements and their status
    - SHA-256 deduplicate evidence items
    - Suppress repeated queries
    - Maintain compact state (not full retrieval history)
    - Track iteration count and enforce limits
    """

    def __init__(self, max_iterations: int = 3):
        self._state = EvidenceState(max_iterations=max_iterations)
        logger.info(f"[EvidenceSummaryState] Initialized (max_iterations={max_iterations})")

    # ------------------------------------------------------------------
    # Property accessors
    # ------------------------------------------------------------------

    @property
    def state(self) -> EvidenceState:
        return self._state

    @property
    def is_complete(self) -> bool:
        return self._state.terminal_state != ""

    @property
    def can_retrieve(self) -> bool:
        return (
            not self.is_complete
            and self._state.iterations_used < self._state.max_iterations
        )

    # ------------------------------------------------------------------
    # Requirements
    # ------------------------------------------------------------------

    def add_requirement(self, req: InformationRequirement) -> None:
        """Add a new information requirement."""
        self._state.requirements.append(req)
        logger.info(
            f"[EvidenceSummaryState] Requirement added: "
            f"id={req.id} metric={req.metric} period={req.period}"
        )

    def add_requirements(self, reqs: List[InformationRequirement]) -> None:
        for r in reqs:
            self.add_requirement(r)

    def update_requirement_status(self, req_id: str, status: str, notes: str = "") -> None:
        """Update the status of a requirement."""
        for req in self._state.requirements:
            if req.id == req_id:
                req.status = status
                if notes:
                    req.notes = notes
                break

    # ------------------------------------------------------------------
    # Evidence deduplication
    # ------------------------------------------------------------------

    @staticmethod
    def compute_hash(content: str) -> str:
        """Compute SHA-256 hash of evidence content."""
        return hashlib.sha256(content.encode("utf-8")).hexdigest()

    @staticmethod
    def compute_evidence_hash(item: Dict[str, Any]) -> str:
        """
        Compute a deterministic SHA-256 hash from evidence fields.
        Include metric, value, period, currency, source, and source_anchor
        so that identical facts from different retrievals are detected.
        """
        content = json.dumps(
            {
                "metric": item.get("metric", ""),
                "metric_definition": item.get("metric_definition", ""),
                "value": item.get("value"),
                "unit": item.get("unit", ""),
                "currency_code": item.get("currency_code", ""),
                "currency_role": item.get("currency_role", ""),
                "fx_rate": item.get("fx_rate"),
                "reporting_period": item.get("reporting_period", ""),
                "accounting_basis": item.get("accounting_basis", ""),
                "scope": item.get("scope", ""),
                "source": item.get("source", ""),
                "source_anchor": item.get("source_anchor", ""),
            },
            sort_keys=True,
            default=str,
        )
        return EvidenceSummaryState.compute_hash(content)

    def is_duplicate(self, evidence_hash: str) -> bool:
        """Check if evidence with this hash already exists."""
        return evidence_hash in self._state.evidence

    def add_evidence(self, item: EvidenceItem) -> bool:
        """
        Add evidence to the state. Returns True if new, False if duplicate.
        """
        if not item.evidence_hash:
            item.evidence_hash = self.compute_evidence_hash(item.to_dict())

        if self.is_duplicate(item.evidence_hash):
            logger.info(
                f"[EvidenceSummaryState] Duplicate suppressed: "
                f"hash={item.evidence_hash[:12]} metric={item.metric}"
            )
            return False

        self._state.evidence[item.evidence_hash] = item
        self._state.evidence_count = len(self._state.evidence)
        logger.info(
            f"[EvidenceSummaryState] Evidence added: "
            f"hash={item.evidence_hash[:12]} metric={item.metric} "
            f"source_tier={item.source_tier}"
        )
        return True

    def add_evidence_batch(self, items: List[EvidenceItem]) -> int:
        """Add multiple evidence items. Returns count of new items added."""
        added = 0
        for item in items:
            if self.add_evidence(item):
                added += 1
        return added

    # ------------------------------------------------------------------
    # Query suppression
    # ------------------------------------------------------------------

    def is_query_repeated(self, query: str) -> bool:
        """Check if this exact query has been asked before."""
        query_hash = self.compute_hash(query.strip().lower())
        return query_hash in self._state.queries_asked

    def record_query(self, query: str) -> None:
        """Record that a query was asked."""
        query_hash = self.compute_hash(query.strip().lower())
        self._state.queries_asked.add(query_hash)

    # ------------------------------------------------------------------
    # Iteration tracking
    # ------------------------------------------------------------------

    def record_iteration(self, query: str, result_count: int) -> None:
        """Record one retrieval iteration."""
        self._state.iterations_used += 1
        self._state.retrieval_log.append({
            "iteration": self._state.iterations_used,
            "query": query[:100],
            "new_evidence_count": result_count,
        })
        logger.info(
            f"[EvidenceSummaryState] Iteration {self._state.iterations_used}/"
            f"{self._state.max_iterations}: {result_count} new evidence items"
        )

    # ------------------------------------------------------------------
    # Requirement satisfaction check
    # ------------------------------------------------------------------

    def evaluate_requirements(self) -> None:
        """Evaluate all requirements against current evidence."""
        satisfied = 0
        missing = 0
        conflicts = 0

        for req in self._state.requirements:
            matching = [
                e for e in self._state.evidence.values()
                if e.metric == req.metric
                and (not req.period or e.reporting_period == req.period)
            ]

            if not matching:
                req.status = MISSING
                missing += 1
                continue

            # Check for conflicts (same metric, same period, different values)
            unique_values = set()
            for ev in matching:
                if ev.value is not None:
                    unique_values.add(ev.value)

            if len(unique_values) > 1:
                # Check if superseded items exist
                active = [ev for ev in matching if ev.verification_status != EVIDENCE_SUPERSEDED]
                active_values = set(ev.value for ev in active if ev.value is not None)
                if len(active_values) <= 1:
                    req.status = VERIFIED
                    satisfied += 1
                else:
                    req.status = CONFLICTING
                    conflicts += 1
            else:
                req.status = VERIFIED if matching[0].verification_status != EVIDENCE_PENDING else FOUND
                if req.status == VERIFIED:
                    satisfied += 1
                else:
                    # Found but not yet verified — treat as found
                    req.status = FOUND
                    satisfied += 1

        self._state.satisfied_count = satisfied
        self._state.missing_count = missing
        self._state.conflict_count = conflicts

    @property
    def all_requirements_satisfied(self) -> bool:
        """Check if all requirements have been satisfied."""
        self.evaluate_requirements()
        return self._state.missing_count == 0 and self._state.conflict_count == 0

    # ------------------------------------------------------------------
    # Terminal state management
    # ------------------------------------------------------------------

    def set_terminal(self, state: str, reason: str) -> None:
        """Set the terminal state and reason."""
        self._state.terminal_state = state
        self._state.terminal_reason = reason
        logger.info(
            f"[EvidenceSummaryState] Terminal state: {state} — {reason}"
        )

    def should_continue(self) -> bool:
        """Check if the orchestration loop should continue."""
        if self.is_complete:
            return False
        if not self.can_retrieve:
            if not self.all_requirements_satisfied:
                self.set_terminal(
                    STATE_RETRIEVAL_LIMIT_REACHED,
                    f"Max iterations ({self._state.max_iterations}) reached. "
                    f"{self._state.missing_count} requirements still missing.",
                )
            return False
        if self.all_requirements_satisfied:
            self.set_terminal(STATE_COMPLETE, "All requirements satisfied")
            return False
        return True

    # ------------------------------------------------------------------
    # Compact state for LLM context
    # ------------------------------------------------------------------

    def get_compact_context(self) -> str:
        """Build a compact evidence summary for LLM context.

        Instead of dumping every retrieved chunk, this produces a
        condensed summary showing what's found, what's missing, and
        what's conflicting.
        """
        sections = []

        # Requirements status
        sections.append("=== EVIDENCE STATUS ===")
        sections.append(f"Iteration: {self._state.iterations_used}/{self._state.max_iterations}")

        req_counts = {
            "REQUIRED": 0,
            "FOUND": 0,
            "VERIFIED": 0,
            "MISSING": 0,
            "CONFLICTING": 0,
        }
        for r in self._state.requirements:
            req_counts[r.status] = req_counts.get(r.status, 0) + 1

        sections.append(
            f"Satisfied: {self._state.satisfied_count} | "
            f"Missing: {self._state.missing_count} | "
            f"Conflicts: {self._state.conflict_count}"
        )

        # Missing requirements
        missing = [r for r in self._state.requirements if r.status == MISSING]
        if missing:
            sections.append("\n=== MISSING REQUIREMENTS ===")
            for r in missing:
                sections.append(f"  - {r.metric} ({r.period})")

        # Conflicting requirements
        conflicting = [r for r in self._state.requirements if r.status == CONFLICTING]
        if conflicting:
            sections.append("\n=== CONFLICTING EVIDENCE ===")
            for r in conflicting:
                items = [
                    e for e in self._state.evidence.values()
                    if e.metric == r.metric
                ]
                sections.append(f"  - {r.metric} ({r.period}):")
                for item in items:
                    sections.append(
                        f"      value={item.value} source={item.source} "
                        f"tier={item.source_tier} status={item.verification_status}"
                    )

        # Verified evidence (compact)
        verified = [r for r in self._state.requirements if r.status == VERIFIED]
        if verified:
            sections.append("\n=== VERIFIED EVIDENCE ===")
            for r in verified:
                items = [
                    e for e in self._state.evidence.values()
                    if e.metric == r.metric
                ]
                for item in items:
                    sections.append(
                        f"  + {item.metric} = {item.value} {item.unit} "
                        f"[{item.reporting_period}] {item.source} (tier {item.source_tier})"
                    )

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------

    def reset(self) -> None:
        """Reset the state for a new orchestration run."""
        self._state = EvidenceState(max_iterations=self._state.max_iterations)
        logger.info("[EvidenceSummaryState] State reset")
